resolver: lts-8.6

nix:
  enable: false
  pure: true
  shell-file: nixpkgs.nix

packages:
  - ./
  - ./xmonad/
  - ./xmonad-contrib/
  - ./x11

extra-deps:
  - X11-xft-0.3.1
  - directory-1.2.7.1
  - xmobar-0.24.3
